# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: test issue 391
permissions: {}

on:
  push:
    branches:
      - test-restrict-kernel-paths-actions

  workflow_dispatch:
    inputs:
      clear-plan:
        description: Clear previous layer plan?
        type: boolean
        required: true
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-build:
    name: Build issue 391 test image
    permissions:
      contents: read
      actions: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: general/recipe-silverblue-main.yml
      rechunk: true
      clear-plan: ${{ inputs.clear-plan || false }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}
