# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: test issue 391
permissions: {}

on:
  push:
    branches:
      - test-restrict-kernel-paths-actions

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-build:
    name: Build issue 391 test image
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/pr_build.yml
    with:
      recipe: general/recipe-silverblue-main.yml
